Add JetStream Unique Tag
nats-io/k8s pull request #493
Opened 2022-04-20 10:52 UTC by ramonberrutti-f3

Add the new unique_tag option to Helm Chart

2022-04-20 13:48 UTC, caleblloyd requested changes

2022-04-20 13:48 UTC, caleblloyd commented on helm/charts/nats/values.yaml
> +    unique_tag:
the `values.yaml` file uses `camelCase` for everything, could you make this `uniqueTag`?

2022-04-20 14:03 UTC, ramonberrutti-f3 commented on helm/charts/nats/values.yaml
> +    unique_tag:
great point. Fixed :)

2022-04-20 14:52 UTC, ramonberrutti-f3 commented
@caleblloyd added also the server_tags option

2022-04-20 18:34 UTC, caleblloyd requested changes

2022-04-20 18:34 UTC, caleblloyd commented on helm/charts/nats/values.yaml
> +  tags:
please call this `serverTags`, would like it to reflect the server configuration key as closely as possible so that users can correlate it to NATS configuration documentation easily

2022-04-21 22:09 UTC, caleblloyd approved these changes

2022-04-21 23:35 UTC, merged