adding hostNetwork and dnsPolicy to helm chart
nats-io/k8s pull request #595
Opened 2022-11-15 21:49 UTC by real-danm

2022-11-16 19:50 UTC, caleblloyd requested changes
Thanks for the contribution.  Please add a description and briefly describe what this PR does.

2022-11-16 19:50 UTC, caleblloyd commented on helm/charts/nats/values.yaml
> +hostNetwork: false
should be under `nats` key as this only applies to the stateful set

2022-11-16 19:50 UTC, caleblloyd commented on helm/charts/nats/values.yaml
> +dnsPolicy: ClusterFirst
should be under `nats` key as this only applies to the stateful set

2022-11-16 19:50 UTC, caleblloyd commented on helm/charts/nats/templates/statefulset.yaml
> +      dnsPolicy: {{ toYaml . | nindent 8 }}
this is always a string, so just put the string here, no need for `toYaml`

2022-11-16 19:50 UTC, caleblloyd commented on helm/charts/nats/templates/statefulset.yaml
> +      hostNetwork: {{ toYaml . | nindent 8 }}
this is always a bool, so just put the bool here, no need for `toYaml`

2022-11-17 14:33 UTC, caleblloyd approved these changes

2022-11-17 14:34 UTC, caleblloyd commented
Looks good to me, @wallyqs could you also take a look?

2022-11-17 16:07 UTC, wallyqs approved these changes
LGTM

2022-11-17 16:47 UTC, merged