fix(surveryor): make configmap fully agnostic
nats-io/k8s pull request #693
Opened 2023-03-28 22:26 UTC by Kriys94

This PR:
- makes the ConfigMap name prefixed by the release name. With the current implementation we cannot deploy 2 surveryor chart in the same namespace
- Able to pass any yaml to the configmap such that we can fit the json output depending of the user need.
```
{
  "name":       "my service",
  "topic":      "email.subscribe.>",
  "jwt":        "jwt portion of creds, must include seed also",
  "seed":       "seed portion of creds, must include jwt also",
  "credential": "/path/to/file.creds",
  "nkey":       "nkey seed",
  "token":      "token",
  "username":   "username, must include password also",
  "password":   "password, must include user also",
  "tls_ca":     "/path/to/ca.pem, defaults to surveyor's ca if one exists",
  "tls_cert":   "/path/to/cert.pem, defaults to surveyor's cert if one exists",
  "tls_key":    "/path/to/key.pem, defaults to surveyor's key if one exists"
}
```

With the values:
```
  jetstream:
    enabled: true
    accounts:
    - name: basic
      username: username
      password: password
```
This will output
```
# Source: surveyor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-surveyor-surveyor-accounts
  labels:
    helm.sh/chart: surveyor-0.16.0
    app.kubernetes.io/name: surveyor
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
data:
  basic.json: |
    {"name":"basic","password":"password","username":"username"}
```

2023-03-29 23:41 UTC, caleblloyd requested changes

2023-03-29 23:41 UTC, caleblloyd commented on helm/charts/surveyor/templates/configmap.yaml
> +    {{ . | toJson }}
Removing the templating on the ca/cert/key is a backwards-compatible breaking change.  you could build out a map variable then merge these templated keys onto it - http://masterminds.github.io/sprig/dicts.html

2023-03-30 23:06 UTC, Kriys94 commented on helm/charts/surveyor/templates/configmap.yaml
> +    {{ . | toJson }}
You are right. Thanks for the review. Here is the out come now

```
# Source: surveyor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-surveyor-accounts
  labels:
    helm.sh/chart: surveyor-0.16.0
    app.kubernetes.io/name: surveyor
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
data:
  test.json: |
    {"name":"test","tls":{"secret":{"name":"test-user-tls"},"tls_ca":"/etc/nats-certs/accounts/test/ca.crt","tls_cert":"/etc/nats-certs/accounts/test/tls.crt","tls_key":"/etc/nats-certs/accounts/test/tls.key"}}
  basic.json: |
    {"name":"basic","password":"password","username":"username"}
```


with these values
```
  jetstream:
    enabled: true
    accounts:
    - name: test
      tls:
        secret:
          name: test-user-tls
        ca: "ca.crt" # optional
        cert: "tls.crt"
        key: "tls.key"
    - name: basic
      username: username
      password: password
```

2023-03-30 23:11 UTC, Kriys94 commented on helm/charts/surveyor/templates/deployment.yaml
> +            name: {{- $fullName }}-accounts
Unfortunately {{- include "surveyor.fullname" }}-accounts didnt work because we are in the scope `.Values.config.jetstream.accounts` so I had to create a higher level variable with `$fullName`

2023-03-31 11:28 UTC, caleblloyd requested changes

2023-03-31 11:28 UTC, caleblloyd commented on helm/charts/surveyor/templates/deployment.yaml
> +            name: {{- $fullName }}-accounts
$ is always the root context so you can also use

`{{ include "surveyor.fullname" $ }}`

2023-03-31 11:28 UTC, caleblloyd commented on helm/charts/surveyor/templates/configmap.yaml
> +    {{ . | toJson }}
TLS keys are still nested under `tls` but need to be at top level

Values should not be mutated, they might be used in other templates 

Here is an example of how to use merge and omit

https://github.com/nats-io/k8s/blob/helm-nats-next/helm/charts/nats-next/files/service.yaml#L16

2023-03-31 20:43 UTC, Kriys94 commented on helm/charts/surveyor/templates/deployment.yaml
> +            name: {{- $fullName }}-accounts
Done. thanks

2023-03-31 20:44 UTC, Kriys94 commented on helm/charts/surveyor/templates/configmap.yaml
> +    {{ . | toJson }}
Done it looks like this now
```
---
# Source: surveyor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-surveyor-accounts
  labels:
    helm.sh/chart: surveyor-0.16.0
    app.kubernetes.io/name: surveyor
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/managed-by: Helm
data:
  test.json: |
    {"name":"test","tls_ca":"/etc/nats-certs/accounts/test/ca.crt","tls_cert":"/etc/nats-certs/accounts/test/tls.crt","tls_key":"/etc/nats-certs/accounts/test/tls.key"}
  basic.json: |
    {"name":"basic","password":"password","username":"username"}
```

2023-04-01 16:29 UTC, caleblloyd approved these changes
LGTM. Do you want to do a patch bump in the Chart.yaml so it publishes?

2023-04-03 08:48 UTC, Kriys94 commented
Done. I changed it to 0.5.1 and I need another approval.

2023-04-03 10:09 UTC, merged